version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/mibilib
    steps:
      - checkout:
          path: ~/mibilib
      - restore_cache:
          key: cache2-{{ checksum "environment.yml" }}
      - run:
          name: Install Python deps in a conda env if not cached
          command: |
            if [[ ! -d ~/miniconda/envs/mibilib ]]; then
                echo "Installing Miniconda ...";
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                bash ~/miniconda.sh -b -f -p ~/miniconda;
                ~/miniconda/bin/conda env create -f environment.yml;
            else
                echo "Using cached Miniconda install";
            fi
            
            echo 'eval "$(~/miniconda/bin/conda shell.bash hook)"' >> $BASH_ENV
      - save_cache:
          key: cache2-{{ checksum "environment.yml" }}
          paths:
            - ~/miniconda/envs/mibilib
      - run:
          name: Run tests
          command: |
            sudo apt-get update
            sudo apt install default-jre
            ~/miniconda/envs/mibilib/bin/coverage run -m py.test mibitracker mibidata scripts
            ~/miniconda/envs/mibilib/bin/coverage html -i --omit=*/tests/*
      - run:
          name: Run pylint on files changed from master
          command: |
            for i in $(git diff origin/master --name-only | grep \\.py$ | grep -v tests); do
              if [[ -f $i ]]; then
                echo "linting $i";
                ~/miniconda/envs/mibilib/bin/pylint $i;
              else
                echo "skipping $i because it was deleted";
              fi
            done
            for i in $(git diff origin/master --name-only | grep tests/.*\\.py$); do
              if [[ -f $i ]]; then
                echo "linting $i";
                ~/miniconda/envs/mibilib/bin/pylint \
                  --disable=protected-access,no-name-in-module,import-error,no-member,unused-argument  \
                $i;
              else
                echo "skipping $i because it was deleted";
              fi
            done
      - store_artifacts:
          path: htmlcov
      - run:
          name: Test setup.py with tox if environment has changed.
          command: |
            echo "Running tox to test setup.py"
            source ~/.bashrc
            ~/miniconda/envs/mibilib/bin/tox

  tag_test:
    working_directory: ~/mibilib
    docker:
      - image: cimg/python:3.11.0 # container for the build job

    steps:
      - checkout:
          path: ~/mibilib
      - run:
          name: Check if tag and setup.py are consistent
          command: |
            python check_tag.py
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
